Repository tikv/client-go, pull requests merged in 2024-12, with the labels that each got.

#1509 retry as stale read on replica
  internal/locate/region_request_state_test.go
  internal/locate/replica_selector.go
  internal/locate/replica_selector_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1504 Fix the problem that adaptive update interval doesn't recovers back and there's too much logs about setting the config (#1502)
  oracle/oracles/pd.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1513 Try to validate read ts for all RPC requests
  .github/workflows/compatibility.yml
  integration_tests/go.mod
  integration_tests/go.sum
  internal/locate/region_cache_test.go
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_state_test.go
  internal/locate/region_request_test.go
  internal/locate/replica_selector_test.go
  oracle/oracle.go
  oracle/oracles/export_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  rawkv/rawkv.go
  tikv/kv.go
  tikv/region.go
  tikv/split_region.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/prewrite.go
  txnkv/txnsnapshot/client_helper.go
  txnkv/txnsnapshot/scan.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1515 Cherry pick bugfix #1054 & #1484 to tidb-7.5 branch
  metrics/metrics.go
  oracle/oracle.go
  oracle/oracles/export_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  tikv/kv.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1517 Support adaptive update interval for low resolution ts (#1484)
  metrics/metrics.go
  oracle/oracle.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  tikv/kv.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1505 *: add the traffic statistic
  internal/client/client.go
  internal/client/metrics_collector.go
  internal/client/metrics_collector_test.go
  internal/locate/region_request.go
  kv/store_vars.go
  tikvrpc/tikvrpc.go
  util/execdetails.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1508 memdb: refactor code of art to make it more understandable
  internal/unionstore/arena/arena.go
  internal/unionstore/art/art.go
  internal/unionstore/art/art_arena.go
  internal/unionstore/art/art_iterator.go
  internal/unionstore/art/art_node.go
  internal/unionstore/art/art_node_test.go
  internal/unionstore/art/art_snapshot.go
  internal/unionstore/art/art_test.go
Labels: enhancement, dco-signoff: yes, lgtm, approved, size/L

#1522 Fix the problem that ttlManager may stop working if no need to lock after retry aggressive locking
  integration_tests/2pc_test.go
  txnkv/transaction/test_probe.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1530 metrics: add StaleRegionFromPDCounter
  internal/locate/region_cache.go
  internal/locate/sorted_btree.go
  metrics/metrics.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1511 [6.5]retry as stale reads and remove back off for server busy errors
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_state_test.go
Labels: dco-signoff: no, size/M

#1525 Upgrade the PD client to adopt the latest refactor
  .github/workflows/compatibility.yml
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/pd_api_test.go
  integration_tests/raw/api_test.go
  integration_tests/split_test.go
  integration_tests/util_test.go
  internal/locate/pd_codec.go
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
  internal/mockstore/mocktikv/cluster.go
  internal/mockstore/mocktikv/pd.go
  oracle/oracles/pd.go
  rawkv/rawkv.go
  tikv/kv.go
  tikv/split_region.go
  util/dns.go
  util/pd_interceptor.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1533 oracle: `setLastTS` always push tso to higher value
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1536 Update the PD client to adopt tikv/pd#8943
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/split_test.go
  internal/mockstore/mocktikv/pd.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1532 *: Optimize executor runtime stats performance
  .github/workflows/compatibility.yml
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/snapshot_test.go
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  txnkv/txnsnapshot/snapshot.go
  util/execdetails.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1535 txnkv: introduce ballast object to batch-get worker
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1538 new codec by keyspace meta
  internal/locate/pd_codec.go
  tikv/region.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1540 change ci reference to original tidb
  .github/workflows/compatibility.yml
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/S

#1541 CI: disable tidb compatible test in merge CI
  .github/workflows/compatibility.yml
Labels: dco-signoff: yes, lgtm, approved, size/XS
