Repository tikv/client-go, pull requests merged in 2024-09, with the labels that each got.

#1455 txn-file: Get first key inside range of both region & txn chunk
  txnkv/transaction/txn_file.go
  util/misc.go
  util/misc_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1456 txn-file: Sort by chunks first during group to batches
  txnkv/transaction/txn_file.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1432 transaction: add hook for async commit to track the life cycle of the async-commit goroutine and secondary lock cleanup goroutine
  integration_tests/2pc_test.go
  integration_tests/async_commit_test.go
  txnkv/transaction/2pc.go
  txnkv/transaction/test_probe.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1433 memdb: fix memdb snapshot get/iter is not actually snapshot (#1393)
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1435 memdb: fix memdb snapshot get/iter is not actually snapshot (#1393)
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1436 memdb: fix memdb snapshot get/iter is not actually snapshot (#1393)
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .golangci.yml
  config/client.go
  internal/locate/region_request_state_test.go
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_test.go
  oracle/oracles/pd.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1461 config: change grpc-keepalive-timeout from uint to float64, for support millisecond timeout
  config/client.go
  config/config_test.go
  internal/client/client.go
  internal/locate/store_cache.go
  tikv/kv.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1463 [pick-8.1] region_request: ignore resource group errors that not relative storage layer (#1354)
  internal/locate/region_request.go
  internal/locate/region_request_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1434 memdb: fix memdb snapshot get/iter is not actually snapshot (#1393)
  .github/workflows/test.yml
  .golangci.yml
  internal/unionstore/memdb.go
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_test.go
  util/misc.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1451 membuffer: implement ART with basic get/set
  internal/unionstore/art/art.go
  internal/unionstore/art/art_arena.go
  internal/unionstore/art/art_node.go
  internal/unionstore/art/art_node_test.go
  internal/unionstore/art/art_test.go
  internal/unionstore/memdb_art.go
  internal/unionstore/memdb_bench_test.go
  internal/unionstore/memdb_norace_test.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1462 [pick-7.5]region_request: ignore resource group errors that not relative storage layer (#1354)
  internal/locate/region_request.go
  internal/locate/region_request_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1465 membuffer: support staging & checkpoint for ART
  internal/unionstore/arena/arena.go
  internal/unionstore/arena/arena_test.go
  internal/unionstore/art/art.go
  internal/unionstore/art/art_node.go
  internal/unionstore/memdb_norace_test.go
  internal/unionstore/memdb_test.go
  internal/unionstore/rbt/rbt.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1466 membuffer: support iterator for ART
  internal/unionstore/art/art.go
  internal/unionstore/art/art_iterator.go
  internal/unionstore/art/art_iterator_test.go
  internal/unionstore/art/art_node.go
  internal/unionstore/memdb_bench_test.go
  internal/unionstore/memdb_norace_test.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1458 feat: Broadcast min_commit_ts for pipelined transactions
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  internal/locate/region_cache.go
  internal/locate/region_request_test.go
  tikv/gc.go
  tikv/kv_test.go
  tikvrpc/tikvrpc.go
  txnkv/transaction/2pc.go
  txnkv/transaction/2pc_test.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/prewrite.go
  txnkv/transaction/test_probe.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1467 membuffer: implement snapshot get and iterator for ART
  internal/unionstore/art/art.go
  internal/unionstore/art/art_iterator.go
  internal/unionstore/art/art_snapshot.go
  internal/unionstore/memdb.go
  internal/unionstore/memdb_art.go
  internal/unionstore/memdb_rbt.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L
