Repository tikv/client-go, pull requests merged in 2024-08, with the labels that each got.

#1412 Fix the problem that statement being oom-killed within DoneAggressive Locking causing the transaction still in aggressive locking state (#1355)
  txnkv/transaction/txn.go
Labels: dco-signoff: yes

#1413 txn-file: Lower log level of "group to batches" to debug
  txnkv/transaction/txn_file.go
Labels: dco-signoff: yes

#1407 fix issue that store's liveness may incorrectly marked as unreachable when the store restarts with label changed
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
  internal/locate/store_cache.go
Labels: dco-signoff: yes

#1415 *: Update golangci-lint to v1.59.1 and fix lint errors
  .github/workflows/test.yml
  .golangci.yml
  internal/unionstore/memdb.go
  util/misc.go
  util/misc_test.go
Labels: dco-signoff: yes

#1416 txn-file: Improve prewrite/commit concurrency when number of txn chunks is small
  txnkv/transaction/txn_file.go
Labels: dco-signoff: yes

#1417 fix issue that store's liveness may incorrectly marked as unreachable when the store restarts with label changed (#1402)
  integration_tests/pd_api_test.go
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
Labels: dco-signoff: yes

#1406 refine region request debug log
  internal/locate/region_request.go
Labels: dco-signoff: yes

#1389 Let memdb cache last traversed node
  internal/unionstore/memdb.go
  internal/unionstore/memdb_arena.go
  internal/unionstore/pipelined_memdb.go
  internal/unionstore/union_store.go
  tikv/unionstore_export.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes

#1410 region cache: batch find regions by key ranges from cache
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
  internal/locate/sorted_btree.go
Labels: dco-signoff: yes

#1418 txn-file: Support RU discount
  config/client.go
  txnkv/transaction/txn_file.go
Labels: dco-signoff: yes

#1411 improve batch efficiency for high throughput workloads
  config/client.go
  internal/client/client.go
  internal/client/client_batch.go
  internal/client/client_test.go
  metrics/metrics.go
  metrics/shortcuts.go
Labels: dco-signoff: yes

#1422 Add GetTimeDetail for SnapshotRuntimeStats
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes

#1423 region_request: remove backoff for stale read
  config/retry/backoff_test.go
  config/retry/config.go
  internal/locate/region_request.go
Labels: dco-signoff: yes

#1430 region_request: remove backoff for stale read (#1423)
  internal/locate/region_request.go
  internal/retry/backoff_test.go
  internal/retry/config.go
Labels: dco-signoff: yes, size/S

#1429 region_request: remove backoff for stale read (#1423)
  internal/locate/region_request.go
  internal/retry/backoff_test.go
  internal/retry/config.go
Labels: dco-signoff: yes, size/S

#1428 region_request: remove backoff for stale read (#1423)
  internal/locate/region_request.go
  internal/retry/backoff_test.go
  internal/retry/config.go
Labels: dco-signoff: yes, size/S

#1427 region_request: remove backoff for stale read (#1423)
  config/retry/backoff_test.go
  config/retry/config.go
  internal/locate/region_request.go
Labels: dco-signoff: yes, size/S

#1393 memdb: fix memdb snapshot get/iter is not actually snapshot
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, approved, size/M, needs-1-more-lgtm

#1426 membuffer: refactor the memdb to support multi implementations
  internal/unionstore/arena/arena.go
  internal/unionstore/arena/arena_test.go
  internal/unionstore/art/art.go
  internal/unionstore/art/art_arena.go
  internal/unionstore/art/art_iterator.go
  internal/unionstore/art/art_node.go
  internal/unionstore/art/art_snapshot.go
  internal/unionstore/memdb.go
  internal/unionstore/memdb_art.go
  internal/unionstore/memdb_bench_test.go
  internal/unionstore/memdb_norace_test.go
  internal/unionstore/memdb_rbt.go
  internal/unionstore/memdb_test.go
  internal/unionstore/mock.go
  internal/unionstore/pipelined_memdb.go
  internal/unionstore/pipelined_memdb_test.go
  internal/unionstore/rbt/rbt.go
  internal/unionstore/rbt/rbt_arena.go
  internal/unionstore/rbt/rbt_iterator.go
  internal/unionstore/rbt/rbt_snapshot.go
  internal/unionstore/rbt/rbt_test.go
  internal/unionstore/union_store.go
  internal/unionstore/union_store_test.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1437 [tidb-cse-7.5] memdb: fix memdb snapshot get/iter is not actually snapshot
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, size/M

#1452 improve region request log for diagnose #1300
  integration_tests/main_test.go
  integration_tests/snapshot_test.go
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_test.go
  metrics/metrics.go
  tikv/region.go
  txnkv/txnsnapshot/client_helper.go
  txnkv/txnsnapshot/snapshot.go
  txnkv/txnsnapshot/test_probe.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1453 memdb: use atomic u64 addr to reduce allocation
  internal/unionstore/arena/arena.go
  internal/unionstore/memdb_art.go
  internal/unionstore/memdb_rbt.go
  internal/unionstore/memdb_test.go
  internal/unionstore/rbt/rbt.go
Labels: dco-signoff: yes, lgtm, approved, size/M
