Repository tikv/client-go, pull requests merged in 2024-11, with the labels that each got.

#1464 [pick-7.1] region_request: ignore resource group errors that not relative storag layer (#1354)
  internal/locate/region_request.go
  internal/locate/region_request_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1485 txn-file: Change switch variable to `DisableTxnFile`
  kv/variables.go
  txnkv/transaction/txn_file.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1482 membuffer: compare the keys of ART by chunk
  internal/unionstore/art/art_iterator.go
  internal/unionstore/art/art_node.go
  internal/unionstore/art/art_node_test.go
  internal/unionstore/memdb_bench_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1487 Fix the problem that statement being oom-killed within DoneAggressiveLocking causing the transaction still in aggressive locking state (#1355)
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1484 Support adaptive update interval for low resolution ts
  metrics/metrics.go
  oracle/oracle.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  tikv/kv.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1490 mod: update pd client
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  internal/client/client_interceptor.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1483 membuffer: fix memory leak in red-black tree
  internal/unionstore/memdb_test.go
  internal/unionstore/rbt/rbt.go
  internal/unionstore/rbt/rbt_iterator.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1492 go.mod: update kvproto
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1486 clean up locks when p-dml is failed
  txnkv/transaction/2pc.go
  txnkv/transaction/pipelined_flush.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1502 Fix the problem that adaptive update interval doesn't recovers back and there's too much logs about setting the config
  oracle/oracles/pd.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1503 memdb: retain old version nodes of ART to satisfy snapshot read
  internal/unionstore/art/art_arena.go
  internal/unionstore/art/art_snapshot.go
  internal/unionstore/art/art_snapshot_test.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1507 Revert "go.mod: update kvproto (#1492)"
  .github/workflows/integration.yml
  .github/workflows/test.yml
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1496 membuffer: fix memory leak in red-black tree (#1483)
  internal/unionstore/memdb.go
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_iterator.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1499 membuffer: fix memory leak in red-black tree (#1483)
  internal/unionstore/memdb.go
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_iterator.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1498 membuffer: fix memory leak in red-black tree (#1483)
  internal/unionstore/memdb.go
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_iterator.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1500 membuffer: fix memory leak in red-black tree (#1483)
  .github/workflows/test.yml
  internal/unionstore/memdb.go
  internal/unionstore/memdb_arena.go
  internal/unionstore/memdb_iterator.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1489 Export commitTS of KVTxn
  integration_tests/1pc_test.go
  integration_tests/2pc_test.go
  integration_tests/assertion_test.go
  integration_tests/async_commit_test.go
  integration_tests/isolation_test.go
  integration_tests/lock_test.go
  txnkv/transaction/test_probe.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/M
