Repository tikv/client-go, pull requests merged in 2024-10, with the labels that each got.

#1470 membuffer: implement cache for ART
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  internal/unionstore/art/art.go
  internal/unionstore/memdb_bench_test.go
  internal/unionstore/memdb_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1471 Do not broadcast txn status when heartbeat fail
  .github/workflows/compatibility.yml
  txnkv/transaction/2pc.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1473 *: upgrade go1.23
  .github/workflows/compatibility.yml
  .github/workflows/integration.yml
  .github/workflows/test.yml
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  integration_tests/go.mod
  internal/unionstore/memdb_norace_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1476 dep: update github.com/dgryski/go-farm
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/S

#1480 region cache: retry scan or batch scan regions when returned region has no leader
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M, type/bugfix

#1477 membuffer: improve ART's code and test coverage
  error/error.go
  internal/unionstore/art/art.go
  internal/unionstore/art/art_arena.go
  internal/unionstore/art/art_iterator.go
  internal/unionstore/art/art_iterator_test.go
  internal/unionstore/art/art_node.go
  internal/unionstore/art/art_node_test.go
  internal/unionstore/art/art_snapshot.go
  internal/unionstore/art/art_test.go
  internal/unionstore/memdb_test.go
  internal/unionstore/rbt/rbt.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL
