Repository tikv/client-go, pull requests merged in 2025-04, with the labels that each got.

#1612 support redact key in logs
  error/error.go
  go.mod
  go.sum
  integration_tests/scan_test.go
  internal/apicodec/codec_v2.go
  internal/locate/region_cache.go
  internal/logutil/hex.go
  internal/mockstore/mocktikv/errors.go
  internal/unionstore/union_iter.go
  kv/key.go
  tikv/split_region.go
  txnkv/rangetask/range_task.go
  txnkv/transaction/2pc.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/prewrite.go
  txnkv/transaction/txn.go
  txnkv/txnlock/lock_resolver.go
  txnkv/txnsnapshot/scan.go
  txnkv/txnsnapshot/snapshot.go
  util/misc.go
  util/redact/redact.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1624 update integration_test/go.mod
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1632 pd: enable OutputMustContainAllKeyRange
  internal/locate/region_cache.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1633 (tidb-8.5) support redact key in logs (#1612)
  error/error.go
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/scan_test.go
  internal/apicodec/codec_v2.go
  internal/locate/region_cache.go
  internal/logutil/hex.go
  internal/mockstore/mocktikv/errors.go
  internal/unionstore/union_iter.go
  kv/key.go
  tikv/split_region.go
  txnkv/rangetask/range_task.go
  txnkv/transaction/2pc.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/prewrite.go
  txnkv/transaction/txn.go
  txnkv/txnlock/lock_resolver.go
  txnkv/txnsnapshot/scan.go
  txnkv/txnsnapshot/snapshot.go
  util/misc.go
  util/redact/redact.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1627 Fix backoff lose info when forked
  config/retry/backoff.go
  config/retry/backoff_test.go
  rawkv/rawkv.go
  tikv/split_region.go
  txnkv/txnlock/lock_resolver.go
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/L, ok-to-test

#1635 tikv: disable health-feedback in next-gen
  config/nextgen_off.go
  config/nextgen_on.go
  tikv/kv.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1619 enable ts validation for normal read
  internal/locate/region_request_test.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1638 apicodec: fix a typo when encoding request for CmdMvccGetByKey
  internal/apicodec/codec_v2.go
Labels: dco-signoff: yes, lgtm, approved, size/XS
