Repository tikv/client-go, pull requests merged in 2025-07, with the labels that each got.

#1673 snapshot: set `ReplicaRead` to false when `ReplicaReadType` fallbacks to `ReplicaReadLeader` (#1663)
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  integration_tests/snapshot_test.go
  internal/locate/replica_selector.go
  internal/locate/replica_selector_test.go
  tikvrpc/tikvrpc.go
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1698 region cache: do not invalidate the valid region cache when new region cache is loaded
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1699 pd client: add valid function for pd client config
  config/config.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1651 metrics: observe tail latencies of batch send/recv
  internal/client/client_batch.go
  metrics/metrics.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1701 region cache: do not invalidate the valid region cache when new region cache is loaded (#1698)
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1702 region cache: do not invalidate the valid region cache when new region cache is loaded (#1698)
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1683 util/async: make TestExecConcurrent stable
  util/async/runloop_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1711 client: make TestSendRequestAsyncTimeout/CanceledOnHandle stable
  internal/client/client_async_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1700 client: split large files and rename unclear fields
  internal/client/client.go
  internal/client/client_async.go
  internal/client/client_batch.go
  internal/client/client_fail_test.go
  internal/client/client_test.go
  internal/client/conn_batch.go
  internal/client/conn_monitor.go
  internal/client/conn_pool.go
  internal/locate/region_cache.go
  internal/locate/store_cache.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1712 region cache: limit key ranges sent to PD in one `BatchScanRegions` gRPC
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1695 txnkv: prevent some actions from being interrupted by kill (#1665)
  integration_tests/2pc_test.go
  internal/locate/region_request.go
  tikvrpc/tikvrpc.go
  txnkv/transaction/2pc.go
  txnkv/transaction/cleanup.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/prewrite.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1694 txnkv: prevent some actions from being interrupted by kill (#1665)
  integration_tests/2pc_test.go
  internal/locate/region_request.go
  tikvrpc/tikvrpc.go
  txnkv/transaction/2pc.go
  txnkv/transaction/cleanup.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/prewrite.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1719 replica selector: do not send replica-read to leader
  integration_tests/snapshot_test.go
  internal/locate/replica_selector.go
  internal/locate/replica_selector_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1715 region cache: Preserve needReloadOnAccess Flag on Region Cache Reload Failure
  internal/locate/region_cache.go
Labels: dco-signoff: yes, lgtm, approved, size/XS, ok-to-test

#1629 txn: fix resolver cache usage for async commit
  integration_tests/async_commit_test.go
  integration_tests/lock_test.go
  txnkv/txnlock/lock_resolver.go
  txnkv/txnlock/lock_resolver_test.go
  txnkv/txnlock/test_probe.go
Labels: dco-signoff: yes, lgtm, approved, size/L, require-LGT3, type/bugfix
