Repository tikv/client-go, pull requests merged in 2025-06, with the labels that each got.

#1650 tests: bump tidb to fix integration tests
  integration_tests/async_commit_test.go
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/pipelined_memdb_test.go
  integration_tests/split_test.go
  integration_tests/util_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1646 *: support async batch get
  config/config.go
  integration_tests/split_test.go
  internal/locate/region_request.go
  metrics/metrics.go
  metrics/shortcuts.go
  tikv/test_util.go
  txnkv/txnsnapshot/client_helper.go
  txnkv/txnsnapshot/snapshot.go
  txnkv/txnsnapshot/snapshot_async.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1666 [tidb-cse-7.5] fix integration test
  integration_tests/async_commit_test.go
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/pd_api_test.go
  integration_tests/raw/api_test.go
  integration_tests/split_test.go
  integration_tests/util_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1661 ci: add next-gen integration tests
  .github/workflows/integration.yml
  integration_tests/health_feedback_test.go
  integration_tests/lock_test.go
  integration_tests/pd_api_test.go
  integration_tests/pd_next_gen.toml
  integration_tests/pipelined_memdb_test.go
  integration_tests/scan_test.go
  integration_tests/snapshot_fail_test.go
  integration_tests/snapshot_test.go
  integration_tests/tikv_next_gen.toml
  integration_tests/util_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1670 tidb-cse-7.5: fix get resource group
  .github/workflows/integration.yml
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/split_test.go
  internal/locate/pd_codec.go
  internal/locate/region_cache.go
  internal/locate/region_request_test.go
  internal/mockstore/mocktikv/pd.go
  util/pd_interceptor.go
Labels: dco-signoff: yes, lgtm, approved, size/XL, ok-to-test, skip-integration-tests

#1665 txnkv: prevent some actions from being interrupted by kill
  integration_tests/2pc_test.go
  internal/locate/region_request.go
  tikvrpc/tikvrpc.go
  txnkv/transaction/2pc.go
  txnkv/transaction/cleanup.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/prewrite.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1680 (tidb-7.5) Support buckets for `ScanRegions` of mocktikv
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
  internal/mockstore/mocktikv/cluster.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1687 tidb-cse-7.5: revert pd client
  .github/workflows/integration.yml
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/split_test.go
  internal/locate/pd_codec.go
  internal/locate/region_cache.go
  internal/locate/region_request_test.go
  internal/mockstore/mocktikv/pd.go
  internal/resourcecontrol/resource_control.go
  kv/store_vars.go
  tikvrpc/tikvrpc.go
  util/pd_interceptor.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1686 region_cache: add ForceRefreshAllStores function
  internal/locate/region_cache.go
Labels: dco-signoff: yes, lgtm, approved, size/XS
