Repository tikv/client-go, pull requests merged in 2025-02, with the labels that each got.

#1566 retry stale read as stale if leader is not accessible
  internal/locate/region_request3_test.go
  internal/locate/region_request_state_test.go
  internal/locate/replica_selector.go
  internal/locate/replica_selector_test.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1567 *: bump pd client
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/M

#1568 (tidb-8.5) Do not set txn scope in snapshot
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1572 (tidb-6.5) Do not set txn scope in snapshot
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1569 (tidb-8.1) Do not set txn scope in snapshot
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1570 (tidb-7.5) Do not set txn scope in snapshot
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1571 (tidb-7.1) Do not set txn scope in snapshot
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1573 sync etcd endpoints immediately after initializing the client
  tikv/kv.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1579 (tidb-6.5) Use global txn scope when validating ts
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1580 (tidb-7.1) Use global txn scope when validating ts
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1581 (tidb-7.5) Use global txn scope when validating ts
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1583 (tidb-8.5) Use global txn scope when validating ts
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1582 (tidb-8.1) Use global txn scope when validating ts
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1584 p-dml: resolve locks concurrently
  internal/locate/region_request.go
  txnkv/transaction/pipelined_flush.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1563 memdb: prevent iterator invalidation
  internal/unionstore/arena/arena.go
  internal/unionstore/art/art.go
  internal/unionstore/art/art_iterator.go
  internal/unionstore/art/art_snapshot.go
  internal/unionstore/memdb_art.go
  internal/unionstore/memdb_bench_test.go
  internal/unionstore/memdb_rbt.go
  internal/unionstore/memdb_test.go
  internal/unionstore/pipelined_memdb.go
  internal/unionstore/union_store.go
  txnkv/transaction/2pc.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1565 locate: refactor RegionRequestSender.SendReqCtx
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1590 (tidb-6.5) Ignore errors in ts validator
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1593 locate: fix the default settings of circuit breaker
  internal/locate/region_cache.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1588 variable: add EnableColumnarExecution variable for kv
  kv/variables.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1594 (tidb-7.5) Validate ts only for stale read
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1591 util: define and implement core interfaces for async api
  util/async/core.go
  util/async/core_test.go
  util/async/runloop.go
  util/async/runloop_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1585 p-dml: resolve locks concurrently (#1584)
  internal/locate/region_request.go
  txnkv/transaction/pipelined_flush.go
Labels: dco-signoff: yes, lgtm, approved, size/XS
