Repository tikv/client-go, pull requests merged in 2025-05, with the labels that each got.

#1636 *: update kvproto version
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test

#1640 txn: provide more information in commit RPC / log mvcc debug info when commit failed for `TxnLockNotFound`
  error/error.go
  error/error_test.go
  internal/apicodec/codec_v2.go
  internal/apicodec/codec_v2_test.go
  txnkv/transaction/commit.go
  txnkv/transaction/pipelined_flush.go
  txnkv/txnlock/lock_resolver.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1642 txn: handle undetermined error in client go
  config/retry/backoff.go
  config/retry/backoff_test.go
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/1pc_test.go
  integration_tests/2pc_test.go
  integration_tests/async_commit_fail_test.go
  integration_tests/go.mod
  integration_tests/go.sum
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_test.go
  internal/locate/replica_selector_test.go
  txnkv/transaction/2pc.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/prewrite.go
  txnkv/txnsnapshot/scan.go
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1618 locate: implement SendReqAsync for RegionRequestSender
  internal/locate/region_request.go
  internal/locate/region_request_state_test.go
  internal/locate/region_request_test.go
  internal/locate/replica_selector_test.go
  internal/mockstore/mocktikv/rpc.go
  tikvrpc/tikvrpc.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL
