Repository tikv/client-go, pull requests merged in 2025-01, with the labels that each got.

#1501 Allow configuring the policy when prewrite encounters lock
  txnkv/transaction/prewrite.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1523 region_request: tiny refactor - init function failpointSendReqResult
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1542 *: bump pd client
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/S

#1512 Handle error invalid_max_ts_update
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1531 pick-6.5: Support adaptive update interval for low resolution ts (#1484)
  metrics/metrics.go
  oracle/oracle.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  tikv/kv.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1545 region_cache: fix a potential data race on store.addr
  internal/locate/region_cache.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1553 *: fix two minor bugs
  internal/locate/region_request.go
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1549 Try to validate read ts for all RPC requests (#1513)
  integration_tests/go.mod
  integration_tests/go.sum
  internal/locate/region_cache_test.go
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_state_test.go
  internal/locate/region_request_test.go
  internal/locate/replica_selector_test.go
  oracle/oracle.go
  oracle/oracles/export_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  rawkv/rawkv.go
  tikv/kv.go
  tikv/region.go
  tikv/split_region.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/prewrite.go
  txnkv/txnsnapshot/client_helper.go
  txnkv/txnsnapshot/scan.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1547 Try to validate read ts for all RPC requests (#1513)
  internal/locate/region_cache_test.go
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_state_test.go
  internal/locate/region_request_test.go
  internal/locate/replica_selector_test.go
  oracle/oracle.go
  oracle/oracles/export_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  rawkv/rawkv.go
  tikv/kv.go
  tikv/region.go
  tikv/split_region.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/prewrite.go
  txnkv/txnsnapshot/client_helper.go
  txnkv/txnsnapshot/scan.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1543 integrate circuitbreaker for region calls
  internal/locate/region_cache.go
  internal/mockstore/mocktikv/pd.go
  tikv/region.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1548 Try to validate read ts for all RPC requests (#1513)
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  internal/locate/region_cache_test.go
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_state_test.go
  internal/locate/region_request_test.go
  oracle/oracle.go
  oracle/oracles/export_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  rawkv/rawkv.go
  tikv/kv.go
  tikv/region.go
  tikv/split_region.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/prewrite.go
  txnkv/txnsnapshot/client_helper.go
  txnkv/txnsnapshot/scan.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1559 txnkv: optimize batch-get by reducing overhead of backoffer
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1494 Allow setting concurrency for pipelined flush and resolveLocks
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/pipelined_memdb_test.go
  metrics/metrics.go
  tikv/kv.go
  txnkv/transaction/2pc.go
  txnkv/transaction/pipelined_flush.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1558 Try to validate read ts for all RPC requests (#1513)
  internal/locate/region_cache_test.go
  internal/locate/region_request.go
  internal/locate/region_request3_test.go
  internal/locate/region_request_state_test.go
  internal/locate/region_request_test.go
  oracle/oracle.go
  oracle/oracles/export_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  rawkv/rawkv.go
  tikv/kv.go
  tikv/region.go
  tikv/split_region.go
  txnkv/transaction/commit.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/prewrite.go
  txnkv/txnsnapshot/client_helper.go
  txnkv/txnsnapshot/scan.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#1557 client: refactor intercepted client
  internal/client/client_interceptor.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1555 *: reduce overhead of codec client
  internal/apicodec/codec.go
  internal/apicodec/codec_v1.go
  internal/apicodec/codec_v2.go
  internal/client/client.go
  internal/client/client_collapse.go
  internal/client/client_test.go
  internal/locate/region_request.go
  internal/locate/region_request_test.go
  internal/mockstore/mocktikv/rpc.go
  tikv/test_util.go
  tikvrpc/cmds_generated.go
  tikvrpc/gen.sh
  tikvrpc/tikvrpc.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1556 metrics: optimize rpc latency related metrics
  internal/client/client.go
  internal/client/metrics_collector.go
  internal/client/metrics_collector_test.go
  metrics/metrics.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1564 client: refactor batch client send loop
  integration_tests/go.mod
  integration_tests/go.sum
  internal/client/client.go
  internal/client/client_batch.go
  tikv/test_util.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1562 avoid copy stack in batch-get
  txnkv/txnsnapshot/snapshot.go
Labels: dco-signoff: yes, lgtm, approved, size/XS
