Repository tikv/client-go, pull requests merged in 2025-03, with the labels that each got.

#1603 p-dml: resolve locks concurrently (#1584)
  internal/locate/region_request.go
  txnkv/transaction/pipelined_flush.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1600 Add a retry when getting ts from PD for validating read ts
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#1516 pdclient: Add caller info to pd client
  internal/locate/pd_codec.go
  internal/locate/region_cache.go
  internal/locate/store_cache.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
  rawkv/rawkv.go
  tikv/kv.go
  txnkv/client.go
  util/pd_interceptor.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1601 locate: fix TestTiKVClientReadTimeout
  internal/locate/region_request.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1595 (tidb-7.1) Validate ts only for stale read
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1597 (tidb-8.5) Validate ts only for stale read
  internal/locate/region_request_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1596 (tidb-8.1) Validate ts only for stale read
  internal/locate/region_request_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1605 *: update pd client
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/S

#1607 Validate ts only for stale read
  internal/locate/region_request_test.go
  oracle/oracles/local.go
  oracle/oracles/mock.go
  oracle/oracles/pd.go
  oracle/oracles/pd_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1606 execdetails: export scheduler write details
  util/execdetails.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1615 Update pd client
  examples/gcworker/go.mod
  examples/rawkv/go.mod
  examples/txnkv/1pc_txn/go.mod
  examples/txnkv/async_commit/go.mod
  examples/txnkv/delete_range/go.mod
  examples/txnkv/go.mod
  examples/txnkv/pessimistic_txn/go.mod
  examples/txnkv/unsafedestoryrange/go.mod
  go.mod
  go.sum
  integration_tests/go.mod
  integration_tests/go.sum
  integration_tests/split_test.go
  internal/mockstore/mocktikv/pd.go
Labels: dco-signoff: yes, lgtm, approved, size/M, skip-integration-tests

#1616 ci: allow use label to skip integration tests
  .github/workflows/integration.yml
Labels: dco-signoff: yes, lgtm, approved, size/XS, skip-integration-tests

#1602 remove useless metric tidb_tikvclient_cop_duration_seconds_bucket
  metrics/metrics.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#1617 [tidb-cse-7.5] *: update pd client
  .github/workflows/test.yml
  go.mod
  go.sum
  internal/locate/pd_codec.go
  internal/locate/region_cache.go
  internal/locate/region_cache_test.go
  internal/locate/region_request_test.go
  internal/mockstore/mocktikv/cluster.go
  internal/mockstore/mocktikv/pd.go
  oracle/oracles/pd.go
  rawkv/rawkv.go
  tikv/kv.go
  tikv/split_region.go
  util/pd_interceptor.go
Labels: dco-signoff: yes, lgtm, approved, size/XL, skip-integration-tests

#1604 client: implement SendRequestAsync for RPCClient
  internal/client/client_async.go
  internal/client/client_async_test.go
  internal/client/client_batch.go
  internal/client/client_collapse.go
  internal/client/client_interceptor.go
  internal/client/mockserver/mock_tikv_service.go
  tikv/client.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#1620 Refine pessimistic lock related metrics and stats
  kv/kv.go
  metrics/metrics.go
  txnkv/transaction/pessimistic.go
  txnkv/transaction/txn.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#1609 metrics: adjust bucket count to reduce metrics data
  metrics/metrics.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#1621 update tidb for integration tests
  .github/workflows/compatibility.yml
  .github/workflows/integration.yml
  integration_tests/go.mod
  integration_tests/go.sum
Labels: dco-signoff: yes, lgtm, approved, size/L
